[phases.setup]
aptPkgs = [
  "libglib2.0-0",
  "libnss3",
  "libnspr4",
  "libdbus-1-3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libatspi2.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libasound2",
  "libpango-1.0-0",
  "libcairo2",
  "libx11-6",
  "libx11-xcb1",
  "libxcb1",
  "libxext6",
  "libxshmfence1",
  "libxtst6",
  "ca-certificates",
  "fonts-liberation"
]
